import SideNav from "@/app/SideNav"

export const metadata = {
  title: 'My todo app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body>
        <SideNav />
        {children}
      </body>
    </html>
  )
}
